services:
  web: 
    image: nginx:latest
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  php:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - db
    
  db:
    image: mysql:8.4.0
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "$DB_DATABASE"
      MYSQL_USER: "$DB_USERNAME"
      MYSQL_PASSWORD: "$DB_PASSWORD"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
