#!/usr/bin/bash

set -o errexit
set -o pipefail

source .env

function up {
    echo "test"
    docker compose up "${@}"
}

function down {
    docker compose down "${@}"
}

function composer {
    docker run --rm --interactive                 \
     -e COMPOSER_CACHE_DIR="/app/.cache/composer" \
     -u "$(id -u):$(id -g)" -v "$(pwd):/app"      \
     -w /app composer:2.7.2 composer "${@}"
}

${@}