<!DOCTYPE html>
<html lang="en">

<head>
    <?php require(__DIR__ . "/../Components/head.phtml"); ?>
    <title>Login</title>
</head>

<body>
    <main class="flex h-screen w-screen items-center justify-center">

        <form action="<?= route("auth.find") ?>" method="post" class="card p-4 w-full mx-4 md:mx-0 md:w-1/2 flex flex-col gap-4">
            <h1 class="text-2xl font-bold text-center">Login</h1>
            <label class="form-label">
                E-mail
                <input name="email" type="email" placeholder="email" class="form-input">
            </label>
            <label class="form-label">
                CPF
                <input name="cpf" type="text" placeholder="cpf" class="form-input">
            </label>
            <button type="submit" class="button p-2 w-full ">Submit</button>
        </form>
    </main>
</body>

</html>