<!DOCTYPE html>
<html lang="en">

<head>
    <?php
    require(__DIR__ . "/../Components/head.phtml");
    ?>

    <title>Register</title>
</head>

<body>
    <main class="grow flex flex-col gap-4">
        <?php
        require(__DIR__ . "/../Components/nav.phtml");
        ?>
        <div class="container mx-auto grow flex flex-col gap-4">
            <h1 class="font-bold text-2xl">Welcome <?= $user["name"] ?></h1>
            <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
                <a href="<?= route("pet.index", ["id" => $user["id"]]) ?>" class="flex flex-col gap-4 hover:bg-blue-600/10 transition-all duration-300 card p-4">
                    <h2 class="font-bold">My Pets</h2>
                    <p>View your registred pets.</p>
                </a>
            </div>
        </div>
    </main>
</body>

</html>