<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <head>
        <link rel="stylesheet" href="/assets/build/style.css">

        <title>Register</title>
    </head>

<body>
    <main>
        <div class="w-screen h-screen flex items-center justify-center">
            <div class="flex flex-col gap-4 items-center">
                <h1>Welcome <?= $name ?></h1>
                <p><?= $isVet ? "vet" : "common user" ?></p>

                <a href="<?= route("auth.logout") ?>">Logout</a>
            </div>
        </div>
    </main>
</body>

</html>