<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <head>
        <link rel="stylesheet" href="/assets/build/style.css">

        <title>Register</title>
    </head>

<body>
    <main class="grow flex flex-col gap-4">
        <?php
        require(__DIR__ . "/../Components/nav.phtml");
        ?>
        <div class="w-full grow flex items-center justify-center">
            <div class="flex flex-col gap-4 items-center">
                <h1>Welcome <?= $name ?></h1>
            </div>
        </div>
    </main>
</body>

</html>