<!DOCTYPE html>
<html lang="en">

<head>
    <?php
    require __DIR__ . "/../Components/head.phtml";
    ?>
    <title><?= $vet["profile"]["name"] ?></title>

</head>

<body>
    <?php require __DIR__ . "/../Components/nav.phtml" ?>
    <main class="container mx-auto grow my-4 flex flex-col gap-4">
        <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
            <?php foreach ($vet["crmv_registers"] as $crmv_register): ?>
                <div class="card p-4">
                    <p>number: <?= $crmv_register["crmv"] ?></p>
                    <p>state: <?= $crmv_register["state"] ?></p>
                </div>
            <?php endforeach; ?>
        </div>
    </main>
</body>

</html>