<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php require(__DIR__ . "/../Components/head.phtml"); ?>
    <title>New Pet</title>
</head>

<body>
    <?php require __DIR__ . "/../Components/nav.phtml" ?>
    <main class="grow my-4 flex justify-center items-center">
        <form action="<?= route("pet.store") ?>" class="card p-4 flex flex-col gap-4" method="post">
            <h1 class="font-bold text-2xl text-center">Pet</h1>
            <label class="form-label">
                Name
                <input name="name" type="text" placeholder="name" class="form-input">
            </label>
            <?php
            if (isset($errors["name"])):
            ?>
                <span class="text-red-500 text-center"><?= $errors["name"] ?></span>
            <?php endif; ?>
            <button type="submit" class="button p-2 w-full">Submit</button>
        </form>
    </main>
</body>

</html>