<!DOCTYPE html>
<html lang="en">

<head>
    <?php require(__DIR__ . "/../Components/head.phtml"); ?>
    <title>Pets</title>
</head>

<body>
    <main class="grow flex flex-col gap-4">
        <?php
        require(__DIR__ . "/../Components/nav.phtml");
        ?>
        <div class="container mx-auto grow flex flex-col gap-4">
            <h1 class="font-bold text-2xl"><?= $profile["name"] ?> Pets</h1>
            <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
                <?php foreach ($pets as $pet): ?>
                    <a href="<?= isset($user) && $user["id"] == $profile["id"] ? route("pet.update", ["id" => $pet->id]) : "" ?>" class="<?= isset($user) && $user["id"] == $profile["id"] ? "" : "pointer-events-none" ?> card p-4 flex flex-col hover:bg-blue-500/15 transition-all duration-300">
                        <h2 class="font-bold"><?= $pet->name ?></h2>
                        <img src='<?= $pet->image ? $pet->image : '/assets/placeholder.jpg' ?>' class="aspect-video rounded-2xl">
                        <?php if (isset($user) && $user["id"] == $profile["id"]): ?>
                            <p>Edit or Delete</p>
                        <?php endif; ?>
                    </a>
                <?php endforeach; ?>
                <?php if (isset($user) && $user["id"] == $profile["id"]): ?>
                    <a href="<?= route("pet.create") ?>" class="card p-4 flex flex-col justify-center hover:bg-blue-500/15 transition-all duration-300">
                        <h2 class="font-bold">New Pet</h2>
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </main>
</body>

</html>