<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php require(__DIR__ . "/../Components/head.phtml"); ?>
    <title><?= $name ?></title>
</head>

<body>
    <?php require __DIR__ . "/../Components/nav.phtml" ?>
    <main class="grow my-4 flex justify-center items-center">
        <form action="<?= route("pet.save", ["id" => $id]) ?>" class="card p-4 flex flex-col gap-4" method="post">
            <h1 class="font-bold text-2xl text-center">Pet</h1>
            <label class="form-label">
                Name
                <input name="name" type="text" placeholder="name" class="form-input" value="<?= $name ?>">
            </label>
            <?php
            if (isset($errors["name"])):
            ?>
                <span class="text-red-500 text-center"><?= $errors["name"] ?></span>
            <?php endif; ?>
            <button type="submit" class="button p-2 w-full">Update</button>
            <a class="button text-center p-2 w-full bg-red-500/50 hover:bg-red-500" href="<?= route("pet.delete", ["id" => $id]) ?>">Delete</a>
        </form>

    </main>
</body>

</html>