<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php require(__DIR__ . "/Components/head.phtml"); ?>
    <title>Document</title>
</head>

<body>
    <main>
        <section class="container mx-auto card p-4 mt-4">
            <h1 class="text-2xl font-bold text-center">Cao-Sulta</h1>
            <div class="flex flex-row justify-end gap-4">
                <a href="<?= route("user.create") ?>" class="button p-4">Register</a>
                <a href="<?= route("auth.new") ?>" class="button p-4">Login</a>
            </div>
        </section>
    </main>

</body>

</html>